In [2]:
import numpy as np

In [3]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
Z1, Z2

(array([4, 7, 5, 6, 8, 4, 7, 6, 9, 5]), array([6, 5, 6, 7, 3, 4, 5, 3, 3, 4]))

In [4]:
np.intersect1d(Z1, Z2)

array([4, 5, 6, 7])

In [5]:
mean = np.mean(Z1)
std = np.std(Z2)
(Z1 - mean) / std

array([-1.54814054,  0.6634888 , -0.81093076, -0.07372098,  1.40069858,
       -1.54814054,  0.6634888 , -0.07372098,  2.13790836, -0.81093076])